"""
Django settings for digicommerce project.
Generated by 'django-admin startproject' using Django 4.0.6.
For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""


from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r2syxqro$7ag7t3xz#bv6hf3-1-4r3o#md_ps8lzx65)v%jmw1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'channels',
    "corsheaders",
    "chatroom",
    'rest_framework',
    "rest_framework.authtoken",
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'import_export',
     "users",
    # 'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digicommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digicommerce.wsgi.application'
ASGI_APPLICATION = 'server.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework.authentication.TokenAuthentication',
    )

}
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'digimart',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#         'USER': 'root',
#         'PASSWORD': '',
       
#     }
# }


DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'digi2',
        'HOST': 'epmis-mysql-project-do-user-7163770-0.a.db.ondigitalocean.com',
        'PORT': '25060',
        'USER': 'doadmin',
        'PASSWORD': 'lewb0gd3tx5wc92d',

    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
MEDIA_URL = '/images/'
MEDIA_ROOT = 'static/images'


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3002",
    "http://localhost:3001", 
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

SITE_ID=1

CORS_ALLOW_ALL_ORIGINS = True
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Number of seconds of inactivity before a user is marked offline
USER_ONLINE_TIMEOUT = 300

# Number of seconds that we will keep track of inactive users for before
# their last seen is removed from the cache
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7
# SENDGRID_API_KEY="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"

# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_BACKEND = "sgbackend.SendGridBackend"
# SENDGRID_API_KEY = "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"
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_HOST_USER = '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'
# EMAIL_HOST_PASSWORD = 'Akindel@401234567'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SENDGRID_API_KEY="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"
# EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
# SENDGRID_API_KEY = os.environ.get("SENDGRID_API_KEY")

# SENDGRID_API_KEY = os.getenv('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')

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER ='apikey' # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
